services:
  exit-node:
    build:
      context: .
      dockerfile: apps/server/Dockerfile

    env_file:
      - apps/server/.env

    ports:
      - "3001:3001"
      - "8080:8080"
      - "51820:51820/udp"

    cap_drop:
      - ALL
    cap_add:
      - NET_ADMIN

    devices:
      - /dev/net/tun:/dev/net/tun

    sysctls:
          net.ipv4.ip_forward: "1"

    volumes:
      - wg-configs:/usr/src/app/configs

    restart: unless-stopped

volumes:
  wg-configs:
