[Interface]
Address = 10.10.1.1/24
PrivateKey = 0BJgPeYqdRo8u99+7e8ZjiwH0pSFY9q3R3wPFbZ/Q0k=
ListenPort = 51820
PostUp = sysctl -w net.ipv4.ip_forward=1
PostUp = iptables -A FORWARD -i %i -j ACCEPT
PostUp = iptables -A FORWARD -o %i -j ACCEPT
PostUp = iptables -t nat -A POSTROUTING -o wlan0 -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT
PostDown = iptables -D FORWARD -o %i -j ACCEPT
PostDown = iptables -t nat -D POSTROUTING -o wlan0 -j MASQUERADE

[Peer]
PublicKey = oVfefuC+o1MdkwQY3a0RyD16N25TwTwuV8xT3PgILgU=
AllowedIPs = 10.10.1.2/32