#!/bin/bash

if type update-alternatives >/dev/null 2>&1; then
    # Remove previous link if it doesn't use update-alternatives
    if [ -L '/usr/bin/metro-vpn' -a -e '/usr/bin/metro-vpn' -a "`readlink '/usr/bin/metro-vpn'`" != '/etc/alternatives/metro-vpn' ]; then
        rm -f '/usr/bin/metro-vpn'
    fi
    update-alternatives --install '/usr/bin/metro-vpn' 'metro-vpn' '/opt/metro-vpn/metro-vpn' 100 || ln -sf '/opt/metro-vpn/metro-vpn' '/usr/bin/metro-vpn'
else
    ln -sf '/opt/metro-vpn/metro-vpn' '/usr/bin/metro-vpn'
fi

# Check if user namespaces are supported by the kernel and working with a quick test:
if ! { [[ -L /proc/self/ns/user ]] && unshare --user true; }; then
    # Use SUID chrome-sandbox only on systems without user namespaces:
    chmod 4755 '/opt/metro-vpn/chrome-sandbox' || true
else
    chmod 0755 '/opt/metro-vpn/chrome-sandbox' || true
fi

if hash update-mime-database 2>/dev/null; then
    update-mime-database /usr/share/mime || true
fi

if hash update-desktop-database 2>/dev/null; then
    update-desktop-database /usr/share/applications || true
fi

# Install apparmor profile. (Ubuntu 24+)
# First check if the version of AppArmor running on the device supports our profile.
# This is in order to keep backwards compatibility with Ubuntu 22.04 which does not support abi/4.0.
# In that case, we just skip installing the profile since the app runs fine without it on 22.04.
#
# Those apparmor_parser flags are akin to performing a dry run of loading a profile.
# https://wiki.debian.org/AppArmor/HowToUse#Dumping_profiles
#
# Unfortunately, at the moment AppArmor doesn't have a good story for backwards compatibility.
# https://askubuntu.com/questions/1517272/writing-a-backwards-compatible-apparmor-profile
if apparmor_status --enabled > /dev/null 2>&1; then
  APPARMOR_PROFILE_SOURCE='/opt/metro-vpn/resources/apparmor-profile'
  APPARMOR_PROFILE_TARGET='/etc/apparmor.d/metro-vpn'
  if apparmor_parser --skip-kernel-load --debug "$APPARMOR_PROFILE_SOURCE" > /dev/null 2>&1; then
    cp -f "$APPARMOR_PROFILE_SOURCE" "$APPARMOR_PROFILE_TARGET"

    # Updating the current AppArmor profile is not possible and probably not meaningful in a chroot'ed environment.
    # Use cases are for example environments where images for clients are maintained.
    # There, AppArmor might correctly be installed, but live updating makes no sense.
    if ! { [ -x '/usr/bin/ischroot' ] && /usr/bin/ischroot; } && hash apparmor_parser 2>/dev/null; then
      # Extra flags taken from dh_apparmor:
      # > By using '-W -T' we ensure that any abstraction updates are also pulled in.
      # https://wiki.debian.org/AppArmor/Contribute/FirstTimeProfileImport
      apparmor_parser --replace --write-cache --skip-read-cache "$APPARMOR_PROFILE_TARGET"
    fi
  else
    echo "Skipping the installation of the AppArmor profile as this version of AppArmor does not seem to support the bundled profile"
  fi
fi

# Install MyCompany VPN native agent and system configuration.

VPN_RESOURCES="/opt/metro-vpn/resources"

VPN_AGENT_SOURCE="$VPN_RESOURCES/native/linux/linux-vpn-agent"
VPN_AGENT_TARGET="/usr/lib/mycompany/linux-vpn-agent"

SYSTEMD_SOURCE="$VPN_RESOURCES/packaging/linux/com.mycompany.vpn.service"
SYSTEMD_TARGET="/usr/lib/systemd/system/com.mycompany.vpn.service"

DBUS_SOURCE="$VPN_RESOURCES/packaging/linux/com.mycompany.vpn.conf"
DBUS_TARGET="/etc/dbus-1/system.d/com.mycompany.vpn.conf"

POLKIT_SOURCE="$VPN_RESOURCES/packaging/linux/com.mycompany.vpn.policy"
POLKIT_TARGET="/usr/share/polkit-1/actions/com.mycompany.vpn.policy"


# Create required directories.

mkdir -p "/usr/lib/mycompany"
mkdir -p "/etc/dbus-1/system.d"
mkdir -p "/usr/share/polkit-1/actions"


# Install native VPN agent.

install -m 755 \
    "$VPN_AGENT_SOURCE" \
    "$VPN_AGENT_TARGET"


# Install systemd service.

install -m 644 \
    "$SYSTEMD_SOURCE" \
    "$SYSTEMD_TARGET"


# Install D-Bus policy.

install -m 644 \
    "$DBUS_SOURCE" \
    "$DBUS_TARGET"


# Install polkit policy.

install -m 644 \
    "$POLKIT_SOURCE" \
    "$POLKIT_TARGET"


# Reload systemd configuration.

systemctl daemon-reload


# Enable and start the VPN agent.

systemctl enable com.mycompany.vpn.service
systemctl restart com.mycompany.vpn.service
